#request
geometry_msgs/PoseStamped start
geometry_msgs/PoseStamped goal
---
#respond
bool success
string message

bool need_action
string connector_id
string action_type

string from_region
string to_region

geometry_msgs/PoseStamped wait_pose
geometry_msgs/PoseStamped connector_pose
geometry_msgs/PoseStamped exit_pose
geometry_msgs/PoseStamped final_goal

float64 down_timeout
float64 up_monitor_timeout
string cancel_policy
